# GitHub actions workflow.
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions

# https://scan.coverity.com/projects/gentoo-pax-utils
name: Coverity Scan

on:
  push:
    branches: [master]

jobs:
  coverity:
    strategy:
      matrix:
        os: [ubuntu-latest]
        cc: [gcc]
    runs-on: ${{ matrix.os }}
    env:
      CC: ${{ matrix.cc }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/unofficial-coverity-scan@v0
      with:
        project: gentoo%2Fpax-utils
        email: vapier@gentoo.org
        token: ${{ secrets.COVERITY_SCAN_TOKEN }}
